import os

Import("env")
libxrhash = env.Library( "xrhash",["xrhash.c","xrhash_fast.c"])
env.Append(LIBPATH=os.getcwd() )
env.Append(CPPPATH=os.getcwd() )

Export("env");

SConscript("tests/SConscript",exports="env")
