env = Environment()
env.Append(CFLAGS="-Wall -Werror")
env.Append(CFLAGS="-g -O0")
env.Library( "xrhash","xrhash.c");

env.Program( "xrhash-test", ["xrhash-test.c","testutils.c"] ,LIBS="xrhash",LIBPATH="." );
